### PR TITLE
Nbytes

### PR DESCRIPTION
**Pull request by abheekg**

### CODE REVIEW

**Comment by maedoc** [comment]
thank you, can you please

- drop chagnes to hist.c
- rebase on master (make sure to pull first)

**Comment by abheekg** [comment]
@maedoc I have intentionally kept the changes to hist. It was just a bug, not any new feature. I will remove it if necessary.
I have already rebased before this PR.

**Comment by maedoc** [comment]
@abheekg you're right, I remember now. Sorry, I've been working heavily on #143 and forgot about that.

**Comment by maedoc** [comment]
:+1: thanks for the quick response on this

**Pull request merged**
